-- =============================================================================
-- Migration: 0001_initial_schema.sql
-- Description: Full MVP table schema for ArtisanForge Gen1
-- Contains: Table definitions and indexes only
-- Does NOT contain: RLS policies (0002), triggers (0003)
-- =============================================================================


-- -----------------------------------------------------------------------------
-- USERS
-- Public profile table — extends Supabase's internal auth.users table.
-- One row per user, auto-created by trigger in 0003_triggers.sql on signup.
-- -----------------------------------------------------------------------------
create table public.users (
  id                    uuid references auth.users on delete cascade primary key,
  username              text unique not null,
  bio                   text,
  avatar_url            text,
  stripe_account_id     text,
  -- Tracks Stripe Connect onboarding state for the creator payout flow
  stripe_account_status text default 'not_connected'
    check (stripe_account_status in ('not_connected', 'pending', 'active', 'restricted')),
  follower_count        int default 0 not null,
  following_count       int default 0 not null,
  is_admin              boolean default false not null,
  created_at            timestamptz default now() not null
);

comment on table public.users is
  'Public creator/buyer profile. Extends auth.users. Auto-created on signup via trigger.';
comment on column public.users.stripe_account_status is
  'not_connected | pending | active | restricted — reflects Stripe Express account state.';
comment on column public.users.is_admin is
  'Single-admin flag. Gated via custom JWT claim in middleware. Only the developer holds this.';


-- -----------------------------------------------------------------------------
-- WORKS
-- A creator's uploaded piece — 3D model, painting, illustration, or t-shirt design.
-- A work is a portfolio item. It becomes sellable when a product row is created for it.
-- -----------------------------------------------------------------------------
create table public.works (
  id             uuid primary key default gen_random_uuid(),
  user_id        uuid references public.users on delete cascade not null,
  title          text not null,
  description    text,
  category       text not null
    check (category in ('3d-models', 'painted-minis', 't-shirt-designs', 'traditional-art', 'digital-art')),
  tags           text[] default '{}',
  is_published   boolean default false not null,
  like_count     int default 0 not null,
  comment_count  int default 0 not null,
  -- Full-text search vector — automatically kept in sync by Postgres.
  -- Searched via the GIN index below. Never write to this column directly.
  search_vector  tsvector generated always as (
                   to_tsvector('english',
                     coalesce(title, '') || ' ' || coalesce(description, '')
                   )
                 ) stored,
  created_at     timestamptz default now() not null,
  updated_at     timestamptz default now() not null
);

comment on table public.works is
  'A creator upload — portfolio item and/or basis for a product listing.';
comment on column public.works.search_vector is
  'Auto-generated tsvector for full-text search. Searched via works_search_idx GIN index.';
comment on column public.works.tags is
  'Free-form tag array. Searched via works_tags_idx GIN index.';

-- Full-text search index
create index works_search_idx on public.works using gin(search_vector);
-- Tag filter index
create index works_tags_idx on public.works using gin(tags);
-- Feed queries: creator's works, ordered by date
create index works_user_id_idx on public.works(user_id);
-- Feed queries: ordered by creation date (New tab)
create index works_created_at_idx on public.works(created_at desc);
-- Feed queries: filter published works efficiently
create index works_is_published_idx on public.works(is_published);


-- -----------------------------------------------------------------------------
-- WORK FILES
-- Individual files attached to a work (STL, OBJ, GLB, images).
-- A work can have multiple files — e.g. an STL + its converted GLB + a preview image.
-- -----------------------------------------------------------------------------
create table public.work_files (
  id                uuid primary key default gen_random_uuid(),
  work_id           uuid references public.works on delete cascade not null,
  file_type         text not null
    check (file_type in ('stl', 'obj', 'glb', 'png', 'jpg', 'jpeg', 'webp')),
  storage_path      text not null,   -- Path within Supabase Storage bucket
  public_url        text,            -- Set for files in works-public bucket
  thumbnail_url     text,            -- 800×800 WEBP, generated by Edge Function
  printify_image_id text,            -- Set after design is pushed to Printify (Phase 5)
  is_download_file  boolean default false not null, -- True = this is the purchasable file
  file_size_bytes   bigint,
  created_at        timestamptz default now() not null
);

comment on table public.work_files is
  'Individual files attached to a work. One work may have multiple files.';
comment on column public.work_files.storage_path is
  'Path within Supabase Storage. Combine with bucket name to form full path.';
comment on column public.work_files.is_download_file is
  'If true, this is the file delivered to buyers on purchase of a digital download product.';

create index work_files_work_id_idx on public.work_files(work_id);


-- -----------------------------------------------------------------------------
-- PRODUCTS
-- A work listed for sale. One work can have multiple product types.
-- product_type drives the fulfillment path on payment.
-- -----------------------------------------------------------------------------
create table public.products (
  id                    uuid primary key default gen_random_uuid(),
  work_id               uuid references public.works on delete cascade not null,
  user_id               uuid references public.users on delete cascade not null,
  product_type          text not null
    check (product_type in ('digital_download', 'printify_pod', 'physical_contact')),
  price_cents           int check (price_cents > 0),     -- Null for physical_contact (price on request)
  -- Printify fields — populated during Phase 5 POD setup
  printify_product_id   text,
  printify_blueprint_id text,
  enabled_variants      jsonb,   -- [{variantId, price_cents, colour, size}]
  mockup_urls           text[] default '{}',
  is_active             boolean default true not null,
  created_at            timestamptz default now() not null
);

comment on table public.products is
  'A sellable product backed by a work. product_type determines the fulfillment path.';
comment on column public.products.product_type is
  'digital_download: file delivery via signed URL | printify_pod: Printify fulfillment | physical_contact: Gen2 / contact creator.';
comment on column public.products.enabled_variants is
  'For printify_pod only. Array of {variantId, price_cents, colour, size} objects.';

create index products_work_id_idx on public.products(work_id);
create index products_user_id_idx on public.products(user_id);
create index products_is_active_idx on public.products(is_active);


-- -----------------------------------------------------------------------------
-- ORDERS
-- Created when a buyer initiates checkout. One order per checkout session.
-- Updated to 'paid' by the Stripe webhook handler on payment_intent.succeeded.
-- -----------------------------------------------------------------------------
create table public.orders (
  id                        uuid primary key default gen_random_uuid(),
  buyer_id                  uuid references public.users on delete restrict not null,
  stripe_payment_intent_id  text unique,
  status                    text default 'pending' not null
    check (status in ('pending', 'paid', 'failed', 'refunded')),
  total_cents               int,
  platform_fee_cents        int,   -- Stored for revenue reporting
  created_at                timestamptz default now() not null
);

comment on table public.orders is
  'A buyer checkout session. Status driven by Stripe webhook events.';
comment on column public.orders.platform_fee_cents is
  'ArtisanForge commission taken on this order. Derived from PLATFORM_COMMISSION_RATE at checkout time.';

create index orders_buyer_id_idx on public.orders(buyer_id);
create index orders_stripe_payment_intent_id_idx on public.orders(stripe_payment_intent_id);


-- -----------------------------------------------------------------------------
-- ORDER ITEMS
-- One row per product in an order. Fulfillment tracked at this level.
-- For digital: download_count tracked here.
-- For POD: printify_order_id and tracking_number stored here.
-- -----------------------------------------------------------------------------
create table public.order_items (
  id                  uuid primary key default gen_random_uuid(),
  order_id            uuid references public.orders on delete cascade not null,
  product_id          uuid references public.products on delete restrict not null,
  seller_id           uuid references public.users on delete restrict not null,
  quantity            int default 1 not null check (quantity > 0),
  unit_price_cents    int not null,
  fulfillment_status  text default 'pending' not null
    check (fulfillment_status in ('pending', 'fulfilled', 'shipped', 'cancelled')),
  -- POD-specific fields
  printify_order_id   text,
  tracking_number     text,
  shipping_address    jsonb,
  -- Digital download tracking
  download_count      int default 0 not null,
  created_at          timestamptz default now() not null
);

comment on table public.order_items is
  'One row per product per order. Fulfillment and download state tracked here.';

create index order_items_order_id_idx on public.order_items(order_id);
create index order_items_seller_id_idx on public.order_items(seller_id);
create index order_items_product_id_idx on public.order_items(product_id);


-- -----------------------------------------------------------------------------
-- FOLLOWS
-- Composite primary key — one row per follower/following pair.
-- Counts maintained on public.users via trigger in 0003_triggers.sql.
-- -----------------------------------------------------------------------------
create table public.follows (
  follower_id   uuid references public.users on delete cascade not null,
  following_id  uuid references public.users on delete cascade not null,
  created_at    timestamptz default now() not null,
  primary key (follower_id, following_id),
  -- Prevent self-follows at the DB level
  constraint no_self_follow check (follower_id != following_id)
);

comment on table public.follows is
  'Follow relationships. Counts denormalised on users table via trigger.';

create index follows_follower_id_idx on public.follows(follower_id);
create index follows_following_id_idx on public.follows(following_id);


-- -----------------------------------------------------------------------------
-- LIKES
-- Composite primary key — one row per user/work pair (no duplicate likes).
-- like_count on works maintained via trigger in 0003_triggers.sql.
-- -----------------------------------------------------------------------------
create table public.likes (
  user_id     uuid references public.users on delete cascade not null,
  work_id     uuid references public.works on delete cascade not null,
  created_at  timestamptz default now() not null,
  primary key (user_id, work_id)
);

comment on table public.likes is
  'Work likes. Composite PK prevents duplicates. Count denormalised on works via trigger.';

create index likes_work_id_idx on public.likes(work_id);
create index likes_user_id_idx on public.likes(user_id);


-- -----------------------------------------------------------------------------
-- COMMENTS
-- Flat in Gen1 — no parent_comment_id. Threaded replies are Gen2.
-- comment_count on works maintained via trigger in 0003_triggers.sql.
-- -----------------------------------------------------------------------------
create table public.comments (
  id          uuid primary key default gen_random_uuid(),
  work_id     uuid references public.works on delete cascade not null,
  user_id     uuid references public.users on delete cascade not null,
  content     text not null check (char_length(content) between 1 and 2000),
  -- parent_comment_id intentionally omitted — threaded replies are Gen2
  created_at  timestamptz default now() not null
);

comment on table public.comments is
  'Flat comments on works. Threaded replies (parent_comment_id) deferred to Gen2.';

create index comments_work_id_idx on public.comments(work_id);
create index comments_user_id_idx on public.comments(user_id);


-- -----------------------------------------------------------------------------
-- NOTIFICATIONS
-- Inserted by Postgres triggers in 0003_triggers.sql on likes, comments,
-- follows, and sales. Delivered to the client via Supabase Realtime.
-- -----------------------------------------------------------------------------
create table public.notifications (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid references public.users on delete cascade not null,  -- recipient
  actor_id    uuid references public.users on delete cascade,           -- who triggered it (null = system)
  type        text not null
    check (type in ('like', 'comment', 'follow', 'sale')),
  entity_id   uuid,   -- work_id, comment_id, order_id etc. depending on type
  is_read     boolean default false not null,
  created_at  timestamptz default now() not null
);

comment on table public.notifications is
  'In-app notifications. Inserted by triggers, pushed to client via Supabase Realtime.';

-- Optimised for the notification bell query: unread notifications for current user
create index notifications_user_id_is_read_idx on public.notifications(user_id, is_read);
create index notifications_user_id_created_at_idx on public.notifications(user_id, created_at desc);


-- -----------------------------------------------------------------------------
-- REPORTS
-- Content moderation. Reporters submit; admin reviews via /admin/reports.
-- -----------------------------------------------------------------------------
create table public.reports (
  id           uuid primary key default gen_random_uuid(),
  reporter_id  uuid references public.users on delete cascade not null,
  entity_type  text not null check (entity_type in ('work', 'comment')),
  entity_id    uuid not null,
  reason       text check (char_length(reason) <= 1000),
  status       text default 'pending' not null
    check (status in ('pending', 'reviewed', 'resolved')),
  created_at   timestamptz default now() not null
);

comment on table public.reports is
  'Content moderation reports. Reviewed manually by admin in /admin/reports.';

create index reports_status_idx on public.reports(status);
create index reports_reporter_id_idx on public.reports(reporter_id);
